#ifndef CONTENT_FRAME_XML_H
#define CONTENT_FRAME_XML_H
#include "ContentPackage.h"
#include <cstdint>
#include <filesystem>
#include <map>
#include <set>
#include <string>
#include <vector>

// Client FrameXML composition for declared world-map floor labels.
//
// The generated Lua is strictly additive. It is loaded from the stock
// Interface/FrameXML/FrameXML.toc, after WorldMapFrame.xml, so every global it
// reads is already defined, and it replaces exactly one stock function --
// WorldMapLevelDropDown_Initialize -- by delegating to the original whenever it
// has no label to offer. No stock FrameXML file is edited, and the only stock
// bytes that change anywhere are the TOC's own line list, which grows by one
// entry inserted after a marker the stock file already carries.
//
// Index correspondence is deliberately literal: a declared floor key is the
// same dropdown row `i` the stock loop enumerates. The generated wrapper keeps
// stock DungeonUsesTerrainMap/floorNum behavior for Blizzard's fallback label,
// so a missing custom label behaves exactly like that row did before.
class ContentFrameXml
{
public:
    // locale -> uppercase map token -> dungeon level index -> label
    using Declared = std::map<std::string,
        std::map<std::string, std::map<std::uint32_t, std::string>>>;

    static std::string const& GeneratedLuaTarget();
    static std::string const& StockTocTarget();
    // Stock Interface/FrameXML/FrameXML.toc line that declares where a modded
    // module is allowed to be added. The insertion is refused unless this exact
    // line appears exactly once, so a reworded or localized TOC cannot silently
    // change where the generated Lua lands in the load order.
    static std::string const& TocInsertionMarker();
    // SHA-256 of the verified stock build-12340 FrameXML.toc. The composition
    // reads only this byte sequence, so the generated TOC differs from stock by
    // exactly one inserted line and nothing else.
    static std::string const& VerifiedStockTocSha256();
    // True for a locale GetLocale() can return on build 12340. A locale the
    // client cannot select is refused at parse time rather than shipped as
    // bytes the client will never read.
    static bool SupportedLocale(std::string const& locale);
    static std::set<std::string> const& SupportedLocales();
    // strupper(internalName), restricted to the ASCII range strupper folds
    // deterministically. This is the only token the generated Lua matches
    // against, so an internal name that cannot survive the fold refuses to carry
    // a label instead of generating a token the client would never match.
    static bool FloorNameToken(std::string const& internalName, std::string& token);
    // Collects every declared floor name of one package and refuses a package
    // that states the same locale/level label twice with different text.
    static bool Collect(std::vector<ContentWorldMap> const& worldMaps,
        Declared& out, std::string& error);
    // Folds one package's declarations into the build-wide set. A second package
    // may contribute a new map or a new locale, but may never restate a label:
    // two packages claiming one level is a build conflict, not a merge.
    static bool Merge(Declared const& package, std::string const& packageKey,
        Declared& out, std::string& error);
    // Deterministic Lua text. Ordering comes from the ordered containers alone,
    // so identical declarations always produce identical bytes.
    static bool ComposeLua(Declared const& floors, std::string& text,
        std::string& error);
    // Stock TOC bytes with exactly one inserted module line.
    static bool ComposeToc(std::vector<std::uint8_t> const& stock,
        std::string& text, std::string& error);
    // Writes generated bytes under the workspace and reads them back, so the
    // staged artifact is verified once in one place like every other composer.
    static bool Stage(std::string const& target, std::string const& text,
        std::filesystem::path const& workspace, std::string& error);
    // Cumulative targets this composer owns when any floor name is declared.
    static std::vector<std::string> const& Targets();
};
#endif
