#include "ContentSpellServer.h"
#include "ContentServerBundle.h"
#include "DatabaseEnv.h"
#include "Field.h"
#include "QueryResult.h"
#include "third_party/json/json.hpp"
#include <algorithm>
#include <cstring>
#include <stdexcept>

using nlohmann::json;
namespace {
auto T=ContentServerBundle::SqlIdentityText;
std::array<std::size_t,64> SF(){return SpellDbcComposer::StringFields();}
bool IsString(std::size_t i,std::size_t& group,std::size_t& locale){for(std::size_t g=0;g<4;++g){auto b=std::array<std::size_t,4>{136,153,170,187}[g];if(i>=b&&i<b+16){group=g;locale=i-b;return true;}}return false;}
bool IsSigned(std::size_t i){return i==0||i==13||i==15||i==41||(i>=52&&i<=70)||(i>=74&&i<=76)||(i>=80&&i<=82)||(i>=110&&i<=115)||i==224||i==228;}
std::int32_t SignedWord(std::uint32_t word){std::int32_t value;std::memcpy(&value,&word,4);return value;}
// Keep localized comparisons independent of the connection's utf8mb4 collation.
std::string SqlValue(ResolvedSpell const&s,std::size_t i){std::size_t g=0,l=0;if(IsString(i,g,l))return ContentServerBundle::SqlText(s.localized[g][l])+" COLLATE utf8mb4_unicode_ci";if(i==47||i==77||i==78||i==79||i==101||i==102||i==103||i==119||i==120||i==121||i==216||i==217||i==218||i==229||i==230||i==231){float f;auto w=s.words[i];std::memcpy(&f,&w,4);return std::to_string(f);}if(IsSigned(i))return std::to_string(SignedWord(s.words[i]));return std::to_string(s.words[i]);}
std::string ColumnType(std::size_t i){std::size_t g=0,l=0;if(IsString(i,g,l)){if(g==2)return "text";if(g==3&&l!=15)return "varchar(550)";return "varchar(100)";}if(i==12||i==14)return "bigint unsigned";if(i==47||i==77||i==78||i==79||i==101||i==102||i==103||i==119||i==120||i==121||i==216||i==217||i==218||i==229||i==230||i==231)return "float";if(IsSigned(i))return "int";return "int unsigned";}
std::string OwnerColumn(std::string const&alias,char const*column){return alias.empty()?column:alias+"."+column;}
std::string Owner(std::string const&alias,std::uint32_t id,std::string const&realm,std::string const&package,std::string const&symbol,std::string const&snapshot){return OwnerColumn(alias,"resource_kind")+"="+T("spell.id")+" AND "+OwnerColumn(alias,"entry")+"="+std::to_string(id)+" AND "+OwnerColumn(alias,"realm_name")+"="+T(realm)+" AND "+OwnerColumn(alias,"package_key")+"="+T(package)+" AND "+OwnerColumn(alias,"symbol")+"="+T(symbol)+" AND "+OwnerColumn(alias,"row_json")+"="+T(snapshot);}
std::string Fields(ResolvedSpell const&s){auto c=ContentSpellServer::Columns();std::string x;for(std::size_t i=0;i<c.size();++i)x+=(i?" AND ":"")+std::string("t.`")+c[i]+"`="+SqlValue(s,i);return x;}
ResolvedSpell ReadRow(QueryResult const&q,ResolvedSpell const& identity){auto f=q->Fetch();auto r=identity;for(std::size_t i=0;i<234;++i){std::size_t g=0,l=0;if(IsString(i,g,l))r.localized[g][l]=f[i].Get<std::string>();else if(i==47||i==77||i==78||i==79||i==101||i==102||i==103||i==119||i==120||i==121||i==216||i==217||i==218||i==229||i==230||i==231){float v=f[i].Get<float>();std::memcpy(&r.words[i],&v,4);}else if(IsSigned(i)){auto v=f[i].Get<std::int32_t>();std::memcpy(&r.words[i],&v,4);}else r.words[i]=f[i].Get<std::uint32_t>();}return r;}
ResolvedSpell ParseSnapshot(std::string const& text){auto v=json::parse(text);ResolvedSpell r;r.packageKey=v.at("package").get<std::string>();r.packageVersion=v.at("packageVersion").get<std::string>();r.symbol=v.at("symbol").get<std::string>();if(v.at("resourceKind").get<std::string>()!="spell.id")throw std::runtime_error("Invalid managed Spell ownership kind");r.id=v.at("id").get<std::uint32_t>();r.copyFrom=v.at("copyFrom").get<std::uint32_t>();r.iconCopyFromSpell=v.at("iconCopyFromSpell").get<std::uint32_t>();r.profile=v.at("profile").get<std::string>();r.words=v.at("words").get<decltype(r.words)>();r.localized=v.at("localized").get<decltype(r.localized)>();if(r.words[0]!=r.id||!SpellDbcComposer::BehaviorMatches(r))throw std::runtime_error("Invalid managed Spell ownership snapshot");return r;}
}
std::vector<std::string> ContentSpellServer::Columns(){
	std::vector<std::string> c={"ID","Category","DispelType","Mechanic","Attributes","AttributesEx","AttributesEx2","AttributesEx3","AttributesEx4","AttributesEx5","AttributesEx6","AttributesEx7","ShapeshiftMask","unk_320_2","ShapeshiftExclude","unk_320_3","Targets","TargetCreatureType","RequiresSpellFocus","FacingCasterFlags","CasterAuraState","TargetAuraState","ExcludeCasterAuraState","ExcludeTargetAuraState","CasterAuraSpell","TargetAuraSpell","ExcludeCasterAuraSpell","ExcludeTargetAuraSpell","CastingTimeIndex","RecoveryTime","CategoryRecoveryTime","InterruptFlags","AuraInterruptFlags","ChannelInterruptFlags","ProcTypeMask","ProcChance","ProcCharges","MaxLevel","BaseLevel","SpellLevel","DurationIndex","PowerType","ManaCost","ManaCostPerLevel","ManaPerSecond","ManaPerSecondPerLevel","RangeIndex","Speed","ModalNextSpell","CumulativeAura","Totem_1","Totem_2"};
	for(auto p:{"Reagent","ReagentCount"})for(int i=1;i<=8;++i)c.push_back(std::string(p)+"_"+std::to_string(i));
	for(auto x:{"EquippedItemClass","EquippedItemSubclass","EquippedItemInvTypes"})c.push_back(x);
	for(auto p:{"Effect","EffectDieSides","EffectRealPointsPerLevel","EffectBasePoints","EffectMechanic","ImplicitTargetA","ImplicitTargetB","EffectRadiusIndex","EffectAura","EffectAuraPeriod","EffectMultipleValue","EffectChainTargets","EffectItemType","EffectMiscValue","EffectMiscValueB","EffectTriggerSpell","EffectPointsPerCombo","EffectSpellClassMaskA","EffectSpellClassMaskB","EffectSpellClassMaskC"})for(int i=1;i<=3;++i)c.push_back(std::string(p)+"_"+std::to_string(i));
	for(auto x:{"SpellVisualID_1","SpellVisualID_2","SpellIconID","ActiveIconID","SpellPriority"})c.push_back(x);
	for(auto p:{"Name_Lang","NameSubtext_Lang","Description_Lang","AuraDescription_Lang"}){for(auto l:{"enUS","enGB","koKR","frFR","deDE","enCN","zhCN","enTW","zhTW","esES","esMX","ruRU","ptPT","ptBR","itIT","Unk"})c.push_back(std::string(p)+"_"+l);c.push_back(std::string(p)+"_Mask");}
	for(auto x:{"ManaCostPct","StartRecoveryCategory","StartRecoveryTime","MaxTargetLevel","SpellClassSet","SpellClassMask_1","SpellClassMask_2","SpellClassMask_3","MaxTargets","DefenseType","PreventionType","StanceBarOrder","EffectChainAmplitude_1","EffectChainAmplitude_2","EffectChainAmplitude_3","MinFactionID","MinReputation","RequiredAuraVision","RequiredTotemCategoryID_1","RequiredTotemCategoryID_2","RequiredAreasID","SchoolMask","RuneCostID","SpellMissileID","PowerDisplayID","EffectBonusMultiplier_1","EffectBonusMultiplier_2","EffectBonusMultiplier_3","SpellDescriptionVariableID","SpellDifficultyID"})c.push_back(x);
	if(c.size()!=234)throw std::runtime_error("Internal spell_dbc descriptor column count mismatch");return c;
}
std::string ContentSpellServer::Snapshot(ResolvedSpell const&s){return json{{"package",s.packageKey},{"packageVersion",s.packageVersion},{"symbol",s.symbol},{"resourceKind","spell.id"},{"id",s.id},{"copyFrom",s.copyFrom},{"iconCopyFromSpell",s.iconCopyFromSpell},{"profile",s.profile},{"words",s.words},{"localized",s.localized}}.dump();}
bool ContentSpellServer::ValidateSchema(std::string&error){auto engine=WorldDatabase.Query("SELECT COUNT(*) FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME IN ('spell_dbc','content_manager_server_resource_owner','content_manager_build_lock') AND ENGINE='InnoDB'");if(!engine||engine->Fetch()[0].Get<std::uint64_t>()!=3){error="Managed Spell apply requires InnoDB spell_dbc and ownership/lock tables";return false;}auto q=WorldDatabase.Query("SELECT COLUMN_NAME,COLUMN_TYPE,IS_NULLABLE FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='spell_dbc' ORDER BY ORDINAL_POSITION");if(!q){error="spell_dbc schema is unavailable";return false;}auto c=Columns();std::size_t i=0;do{auto f=q->Fetch();std::size_t g=0,l=0;bool text=IsString(i,g,l);if(i>=c.size()||f[0].Get<std::string>()!=c[i]||f[1].Get<std::string>()!=ColumnType(i)||f[2].Get<std::string>()!=(text?"YES":"NO")){error="spell_dbc column layout differs from the exact build-12340 schema at ordinal "+std::to_string(i+1);return false;}++i;}while(q->NextRow());if(i!=c.size()){error="spell_dbc column count differs from build-12340 descriptor";return false;}return true;}
bool ContentSpellServer::Occupancy(std::string const&realm,std::vector<ItemAllocation> const&retained,std::set<std::uint32_t>&occupied,std::string&error){occupied.clear();auto rows=WorldDatabase.Query("SELECT ID FROM spell_dbc UNION ALL SELECT 0");if(!rows){error="Cannot inspect spell_dbc occupancy; allocation refused";return false;}do{auto id=rows->Fetch()[0].Get<std::uint32_t>();if(id)occupied.insert(id);}while(rows->NextRow());auto owners=WorldDatabase.Query("SELECT entry,package_key,symbol,row_json FROM content_manager_server_resource_owner WHERE realm_name="+T(realm)+" AND resource_kind="+T("spell.id")+" UNION ALL SELECT 0,NULL,NULL,NULL");if(!owners){error="Cannot inspect managed Spell ownership";return false;}do{auto f=owners->Fetch();auto id=f[0].Get<std::uint32_t>();if(!id)continue;auto package=f[1].Get<std::string>(),symbol=f[2].Get<std::string>();auto lease=std::find_if(retained.begin(),retained.end(),[&](auto const&a){return a.realm==realm&&a.resourceKind=="spell.id"&&a.packageKey==package&&a.symbol==symbol&&a.value==id;});if(lease==retained.end()){error="Managed Spell ownership lacks matching retained allocation";return false;}try{auto expected=ParseSnapshot(f[3].Get<std::string>());if(expected.id!=id||expected.packageKey!=package||expected.symbol!=symbol){error="Managed Spell ownership identity mismatch";return false;}bool exists=false;ResolvedSpell current;if(!Check(expected,realm,exists,current,error)||!exists)return false;}catch(std::exception const&e){error=e.what();return false;}occupied.erase(id);}while(owners->NextRow());return true;}
bool ContentSpellServer::Check(ResolvedSpell const&s,std::string const&realm,bool&exists,ResolvedSpell&current,std::string&error){exists=false;auto count=WorldDatabase.Query("SELECT COUNT(*) FROM spell_dbc WHERE ID="+std::to_string(s.id));if(!count){error="Cannot inspect spell_dbc";return false;}auto n=count->Fetch()[0].Get<std::uint64_t>();if(n>1){error="Duplicate spell_dbc ID";return false;}if(!n)return true;auto owner=WorldDatabase.Query("SELECT row_json FROM content_manager_server_resource_owner WHERE resource_kind="+T("spell.id")+" AND entry="+std::to_string(s.id)+" AND realm_name="+T(realm)+" AND package_key="+T(s.packageKey)+" AND symbol="+T(s.symbol));if(!owner){error="Existing spell_dbc row is not owned by this Content Manager resource";return false;}try{auto snapshot=owner->Fetch()[0].Get<std::string>();auto previous=ParseSnapshot(snapshot);if(previous.id!=s.id||previous.packageKey!=s.packageKey||previous.symbol!=s.symbol){error="Managed spell ownership identity mismatch";return false;}auto q=WorldDatabase.Query("SELECT * FROM spell_dbc WHERE ID="+std::to_string(s.id));if(!q){error="Cannot read complete spell_dbc row";return false;}current=ReadRow(q,previous);exists=true;if(snapshot!=Snapshot(current)){error="Managed spell ownership snapshot differs from current row";return false;}}catch(std::exception const&e){error=e.what();return false;}return true;}
std::string ContentSpellServer::Condition(ResolvedSpell const&s,std::string const&realm,bool exists){if(!exists)return "NOT EXISTS(SELECT 1 FROM spell_dbc WHERE ID="+std::to_string(s.id)+") AND NOT EXISTS(SELECT 1 FROM content_manager_server_resource_owner WHERE resource_kind="+T("spell.id")+" AND entry="+std::to_string(s.id)+")";return "EXISTS(SELECT 1 FROM spell_dbc t JOIN content_manager_server_resource_owner o ON o.entry=t.ID AND o.resource_kind="+T("spell.id")+" WHERE "+Fields(s)+" AND "+Owner("o",s.id,realm,s.packageKey,s.symbol,Snapshot(s))+")";}
std::vector<std::string> ContentSpellServer::ApplySql(ResolvedSpell const&d,ResolvedSpell const&c,std::string const&realm,bool exists,std::uint32_t build,std::string const&hash){auto cols=Columns();std::string values;for(std::size_t i=0;i<234;++i)values+=(i?",":"")+SqlValue(d,i);std::vector<std::string> sql;if(exists)sql.push_back("DELETE FROM spell_dbc WHERE ID="+std::to_string(d.id));sql.push_back("INSERT INTO spell_dbc VALUES ("+values+")");if(exists)sql.push_back("UPDATE content_manager_server_resource_owner o SET row_json="+T(Snapshot(d))+",applied_build="+std::to_string(build)+",artifact_sha256="+T(hash)+" WHERE "+Owner("o",d.id,realm,d.packageKey,d.symbol,Snapshot(c)));else sql.push_back("INSERT INTO content_manager_server_resource_owner(resource_kind,entry,realm_name,package_key,symbol,row_json,applied_build,artifact_sha256) VALUES("+T("spell.id")+","+std::to_string(d.id)+","+T(realm)+","+T(d.packageKey)+","+T(d.symbol)+","+T(Snapshot(d))+","+std::to_string(build)+","+T(hash)+")");return sql;}
std::string ContentSpellServer::VerificationSql(ResolvedSpell const&s,std::string const&realm,std::uint32_t build,std::string const&hash){return "SELECT COUNT(*) FROM content_manager_server_resource_owner WHERE "+Owner("",s.id,realm,s.packageKey,s.symbol,Snapshot(s))+" AND applied_build="+std::to_string(build)+" AND artifact_sha256="+T(hash);}
bool ContentSpellServer::Verify(ResolvedSpell const&s,std::string const&realm,std::uint32_t build,std::string const&hash,std::string&error){bool exists=false;ResolvedSpell current;if(!Check(s,realm,exists,current,error)||!exists||Snapshot(current)!=Snapshot(s)){if(error.empty())error="Managed spell row missing or drifted";return false;}auto q=WorldDatabase.Query(VerificationSql(s,realm,build,hash));if(!q||q->Fetch()[0].Get<std::uint64_t>()!=1){error="Managed spell ownership provenance mismatch";return false;}return true;}
